config/routes.rb
Rails.application.routes.draw do
  # get 'welcome/homepage'
  get 'home', to: "welcome#homepage"
  get 'media', to: "welcome#media"
  root 'welcome#homepage'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end

  def media
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dante Alvarado-Leon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/media.html.erb
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Dante Alvarado-Leon</title>
	<!--fonts-->
		<link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
	<!--//fonts-->
		<link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
		<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
	<!-- for-mobile-apps -->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="keywords" content="Dante Alavarado-Leon, MentorRoom " />
		<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- //for-mobile-apps -->
	<!-- js -->
		<script type="text/javascript" src="js/jquery.min.js"></script>
	<!-- js -->
	<!-- start-smooth-scrolling -->
		<script type="text/javascript" src="js/move-top.js"></script>
		<script type="text/javascript" src="js/easing.js"></script>
		<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
		</script>
	<!-- start-smooth-scrolling -->

</head>
<body>
<!-- banner -->
<div class="banner" >
	<div class="container"> 
		<div class="top-header row">
			<script src="assets/classie.js"></script>
			<!--top-nav -->
			<!-- <div class="logo">
				<a href="#"><img src="assets/logo.png" alt=""/></a>
			</div> -->

			<div class="top-nav">
				<%= link_to "about", "#{root_path}#about", class: "media-link"  %>

				<%= link_to "skills", "#{root_path}#skills", class: "media-link"  %>

				<%= link_to 'portfolio', "#{root_path}#portfolio", class: "media-link" %> 

				<%= link_to "blog", "#{root_path}#blog", class: "media-link"  %>

				<%= link_to 'media', media_path, class: "media-link" %> 

				<%= link_to "contact", "#{root_path}#contact", class: "media-link"  %>

				<div class="clearfix"> </div>
   
			</div>

	


			<!-- -start-click-drop-down-menu -->
			        <!-- start-dropdown-->
			         <script type="text/javascript">
						var $ = jQuery.noConflict();
							$(function() {
								$('#activator').click(function(){
									$('#box').animate({'top':'0px'},900);
								});
								$('#boxclose').click(function(){
								$('#box').animate({'top':'-1000px'},900);
								});
							});
							$(document).ready(function(){
							//Hide (Collapse) the toggle containers on load
							$(".toggle_container").hide(); 
							//Switch the "Open" and "Close" state per click then slide up/down (depending on open/close state)
							$(".trigger").click(function(){
								$(this).toggleClass("active").next().slideToggle("slow");
									return false; //Prevent the browser jump to the link anchor
							});
												
						});
					</script>
			<!-- -//End-click-drop-down-menu -->
			<!-- <div class="clearfix"> </div> -->
		</div>



		<div class="banner-info">
			<!-- <div class="banner-left">
				<img class="img-circle" src="assets/1"/>
			</div> -->
			<div class="banner-font">
				<h1>WELCOME TO MY MEDIA</h1>
				<div class="border"></div>
				<!-- <h2>ENTREPRENEUR & TECH ENTHUSIAST</h2> -->
				<!-- <p> In one line: I have a love for tech, but a passion for people.</p> -->
				
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<!-- /header-banner -->


<!--social entrepreneurship-->
<div class="blog" id="entrepreneurship">
	<div class="container">
		<div class="blog-info text-center">
			<h3>SOCIAL ENTREPRENEURSHIP IN ACTION!</h3>
			<div class="strip text-center"><img src="assets/blog.png" alt=" "/></div>
		</div>
		<div class="blog-grids">


			<div class="col-md-4 blog-text-info">
				<div class="blog-grid">
					<iframe width="349.98px" height="207" src="https://www.youtube.com/embed/sd_4R8D0ytg" frameborder="0" allowfullscreen></iframe>
					<div class="blog-text">
						<a href="https://www.youtube.com/embed/sd_4R8D0ytg">Kapor Capital Pitch Competition</a>
						<div class="stripa"></div>
						<p>Selected out of 90 Startups to pitch at the 2nd Annual People Ops Tech Competition.</p>
					</div>
				
			
				</div>
			</div>


			<div class="col-md-4 blog-text-info">
				<div class="blog-grid">
					<!-- <a href="single.html"><img src="assets/mrweb" alt=""/></a> -->

					<iframe width="349.98px" height="207" src="https://www.youtube.com/embed/FNakfk2RRkc" frameborder="0" allowfullscreen></iframe>

					<div class="blog-text">
						<a href="https://www.mentorroom.co/photos">MentorRoom - Recap of 2016!</a>
						<div class="stripa"></div>
						<p>Amazing experience leading a virtual mentorship initiative for 100 participants to help first-generation students at UC Berkeley by pairing them with Google mentors</p>
					</div>
				
				</div>
			</div>


			<div class="col-md-4 blog-text-info">
				<div class="blog-grid">

					<iframe width="349.98px" height="207" src="https://www.youtube.com/embed/8mBkcxBcqAA" frameborder="0" allowfullscreen></iframe>

					<div class="blog-text">
						<a href="https://www.youtube.com/embed/8mBkcxBcqAA">"A Relentless Journey"</a>
						<div class="stripa"></div>
						<p>Developed a short documentary about my life for the Authentic Berkeley Program. My movie was showcased at the Educational Opportunity Program Awards Ceremony.</p>
					</div>
				
				</div>
			</div>

			<div class="col-md-4 blog-text-info">
				<div class="blog-grid">
					<iframe width="349.98px" height="207" src="https://www.youtube.com/embed/XRq8LA-g6pM" frameborder="0" allowfullscreen></iframe>
					<div class="blog-text">
						<a href="https://www.youtube.com/embed/XRq8LA-g6pM">TeenTech SF - STEM Panel Speaker</a>
						<div class="stripa"></div>
						<p>I was invited to share about my experiences interning at Facebook and being a student at UC Berkeley with the TTSF Community.</p>
					</div>
				
					
				</div>
			</div>

			<div class="col-md-4 blog-text-info">
				<div class="blog-grid">
					<iframe width="349.98px" height="207" src="https://www.youtube.com/embed/uNPg3ZIcIXU" frameborder="0" allowfullscreen></iframe>
					<div class="blog-text">
						<a href="http://www.loftcsl.org/programs/loft-coder-summit/">Latino LOFT Coder Summit </a>
						<div class="stripa"></div>
						<p>Helped develop the initiative to connect Latinx coders by hosting summits all around the U.S.</p>
					</div>
				
					
				</div>
			</div>

			<div class="clearfix"></div>
		</div>
	</div>
</div>
<!--//social entrepreneurship-->



<!--adventures-->
<div class="blog" id="adventures">
	<div class="container">
		<div class="blog-info text-center">
			<h3>SELECTED ADVENTURES</h3>
			<h4>Following my heart everywhere I go, in pursuit of excellence!</h4>
			<div class="strip text-center"><img src="assets/blog.png" alt=" "/></div>
		</div>
		<div class="blog-grids">


			<div class="col-md-4 blog-text-info">
				<div class="blog-grid">
					<img src="assets/president" alt=""/>
					<div class="blog-text">
						<p class="adventures-font" >On a Mission to Design a Better World for All!</p>
						<div class="stripa"></div>
						<p>Practicing for my presidential speech in 2032!</p>
					</div>
				
			
				</div>
			</div>


			<div class="col-md-4 blog-text-info">
				<div class="blog-grid">
					<!-- <a href="single.html"><img src="assets/mrweb" alt=""/></a> -->

					<img src="assets/mrgoogle" alt=""/>

					<div class="blog-text">
						<a href="https://www.mentorroom.co/photos">Founded MentorRoom</a>
						<div class="stripa"></div>
						<p>Launched a closed beta program in partnership with Google and connected 50 undergrads with 50 Google software engineers, product managers, and program managers for mentorship. Accomplished over 450 hours of mentorship and raised $15k for the program.</p>
					</div>
				
				</div>
			</div>


			<div class="col-md-4 blog-text-info">
				<div class="blog-grid">

					<img src="assets/hongkong" alt=""/>

					<div class="blog-text">
						<p class="adventures-font" >India to Hong Kong</p>
						<div class="stripa"></div>
						<p>Selected as one of 30 scholars to work alongside corporate partners and government officials to build a social impact model in Andhra Pradesh contingent with the "100 Smart Cities Plan" in India.</p>
					</div>
				
				</div>
			</div>

			<div class="col-md-4 blog-text-info">
				<div class="blog-grid">
					<img src="assets/manos" alt=""/>
					<div class="blog-text">
						<p class="adventures-font">Manos Accelerator - Entrepreneur in Residence</p>
						<div class="stripa"></div>
						<p>My sophomore year I was selected to participated in a Silicon Valley accelerator out of 70+ startups around the world. It was a great learning experience!</p>
					</div>
				
					
				</div>
			</div>

			

			<div class="clearfix"></div>
		</div>
	</div>
</div>
<!--//adventures-->





<!-- <div class="contact-back"></div> -->


<!--contact-->
<div class="contact" >
	<div class="container">
		<div class="contact-info text-center">
			<h3>CONTACT ME</h3>
			<div class="strip text-center"><img src="assets/con1.png" alt=" "/></div>
		</div>

		<!-- <div> 
			<h3 class="contact-grids col-md-5 contact-left">Connect with me on LinkedIn</h3>
		</div> -->
		<div class=" contact-grids">
			<div class="text-center">
				<h3 class="white-text">Connect with me on <a class="darkblue" href="https://www.linkedin.com/in/dantealvaradoleon/">LinkedIn</a>!</h3>
				
			</div>
		</div>
			
	</div>
</div>
<!--//contact-->

<!-- <div class="footer-top"></div> -->


<!--resume-->
<!-- <div class="resume text-center">
	<div class="container">
		<div class="strip text-center"><a href="#"><img src="assets/down.png" alt=" "/></a></div>
		<div class="down"><a href="#">Download My Resume</a></div>
	</div>
</div> -->
<!--//resume-->

<!--footer-->
<div class="footer">
	<div class="container">
		<p>Made with excitement by Dante Alvarado-Leon :)</p>
	</div>
</div>
<!--//footer-->
<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
			*/
								
			$().UItoTop({ easingType: 'easeOutQuart' });
								
			});
	</script>
<!-- //here ends scrolling icon -->
</body>
</html>